import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import Progress from '@/components/progress/progress';
import Component1 from '@/components/mainForm/Form1/component1';
import { component2 as Component2 } from '@/components/mainForm/Form2/component2';
import { component3 as Component3 } from '@/components/mainForm/Form3/component3';
import { component4 as Component4 } from '@/components/mainForm/Form4/component4';
import Component5 from '@/components/mainForm/Form5/component5';
import context from '@/context/context';
import { useState } from 'react';
export default function Home() {
  let [val, chval] = useState('1');
  let [tt, chtt] = useState(0);
  function totalcalc(data: number) {
    chtt(tt + data);
  }
  function changeMain(order: String) {
    if (val == '1') {
      return <Component1 />;
    } else if (val == '2') {
      return <Component2 sendDataToParent={totalcalc} />;
    } else if (val == '3') {
      return <Component3 sendDataToParent={(tt, totalcalc)} />;
    } else if (val == '4') {
      return <Component4 cost={tt} />;
    } else {
      return <Component5 />;
    }
  }
  return (
    <>
      <Head>
        <title>Multi Step Form</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <context.Provider value={[val, chval]}>
        <div className={styles.body}>
          <div className={styles.form}>
            <div className={styles.progress}>
              <Progress />
            </div>
            <div className={styles.main}>{changeMain(val)}</div>
          </div>
        </div>
      </context.Provider>
    </>
  );
}
